### ISSUE TITLE
what is my your own bowtie index

### ISSUE THREAD

**Issue by WeichenZhou** [Boyle-Lab/SEMpl#16]
Hi,
I was trying to install SMEpl and saw in the manual of installation:
''Symlink to bowtie index location (use your own index location): ln -s /data/genomes/hg19/bowtie_index/ data''.
I was wondering do I need to install bowtie and specify some index file to it?

Thanks a lot!
Arthur

**Comment by sierranishizaki** [comment]
Hello Arthur, 

Thank you for your question. Bowtie is installed when following the SEMpl installation protocol. A bowtie index is required and you will need to build or download a bowtie index matching the genome of the ChIP-seq/DNase data you plan to use. 

Hope this helps, 
Sierra

**Comment by WeichenZhou** [comment]
Thanks! I'll let you know if I have more questions. @sierranishizaki
