### ISSUE TITLE
installation issue "error: use of deleted function 'XXXX' "

### ISSUE THREAD

**Issue by ai358** [Boyle-Lab/SEMpl#17]
Hi, 
I have difficulties compiling SEMpl, I did the symbollink to bowtie index 
this way :   
`wget "ftp://ftp.ccb.jhu.edu/pub/data/bowtie2_indexes/hg19.zip"`
`unzip hg19.zip`
`mkdir -p data/genomes/hg19/bowtie_index/`

Then I followed your instructions
 'git clone --recurse-submodules https://github.com/Boyle-Lab/SEMpl.git`
`cd SEMpl/lib/libBigWig
make
cd ..
make
mv */*.so .
cd ..
 In SEMpl directory
ln -s ../data/genomes/hg19/bowtie_index/ data
make 
`
here the output : 
`[SEMpl]$ make 
g++ -Wall -Werror -pedantic --std=c++11 -I. -pthread -O3 -DDEBUG -Wno-variadic-macros -Wno-unused-local-typedefs -Wno-enum-compare -Wno-unused-result -c src/bowtie_genome_map.cpp -o obj/bowtie_genome_map.o
src/bowtie_genome_map.cpp: In function ‘void bowtie_genome_map(int, const string&, const string&, const string&, const string&, int, bool)’:
src/bowtie_genome_map.cpp:32:44: error: use of deleted function ‘std::basic_stringstream<char>::basic_stringstream(const std::basic_stringstream<char>&)’
     std::stringstream IN = exec(cmd.c_str()); // stringstream instead of writing to a file
                                            ^
In file included from src/common.hpp:6:0,
                 from src/bowtie_genome_map.cpp:2:
/usr/include/c++/4.8.2/sstream:502:11: note: ‘std::basic_stringstream<char>::basic_stringstream(const std::basic_stringstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_stringstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.8.2/sstream:502:11: error: use of deleted function ‘std::basic_iostream<char>::basic_iostream(const std::basic_iostream<char>&)’
In file included from /usr/include/c++/4.8.2/fstream:38:0,
                 from src/iterativeSEM.hpp:14,
                 from src/bowtie_genome_map.cpp:1:
/usr/include/c++/4.8.2/istream:795:11: note: ‘std::basic_iostream<char>::basic_iostream(const std::basic_iostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_iostream
           ^
/usr/include/c++/4.8.2/istream:795:11: error: use of deleted function ‘std::basic_istream<char>::basic_istream(const std::basic_istream<char>&)’
/usr/include/c++/4.8.2/istream:58:11: note: ‘std::basic_istream<char>::basic_istream(const std::basic_istream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8.2/istream:58:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.8.2/ios:44:0,
                 from /usr/include/c++/4.8.2/istream:38,
                 from /usr/include/c++/4.8.2/fstream:38,
                 from src/iterativeSEM.hpp:14,
                 from src/bowtie_genome_map.cpp:1:
/usr/include/c++/4.8.2/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8.2/ios:42:0,
                 from /usr/include/c++/4.8.2/istream:38,
                 from /usr/include/c++/4.8.2/fstream:38,
                 from src/iterativeSEM.hpp:14,
                 from src/bowtie_genome_map.cpp:1:
/usr/include/c++/4.8.2/bits/ios_base.h:786:5: error: ‘std::ios_base::ios_base(const std::ios_base&)’ is private
     ios_base(const ios_base&);
     ^
In file included from /usr/include/c++/4.8.2/ios:44:0,
                 from /usr/include/c++/4.8.2/istream:38,
                 from /usr/include/c++/4.8.2/fstream:38,
                 from src/iterativeSEM.hpp:14,
                 from src/bowtie_genome_map.cpp:1:
/usr/include/c++/4.8.2/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8.2/fstream:38:0,
                 from src/iterativeSEM.hpp:14,
                 from src/bowtie_genome_map.cpp:1:
/usr/include/c++/4.8.2/istream:795:11: error: use of deleted function ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)’
     class basic_iostream
           ^
In file included from /usr/include/c++/4.8.2/istream:39:0,
                 from /usr/include/c++/4.8.2/fstream:38,
                 from src/iterativeSEM.hpp:14,
                 from src/bowtie_genome_map.cpp:1:
/usr/include/c++/4.8.2/ostream:58:11: note: ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ostream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8.2/ostream:58:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.8.2/fstream:38:0,
                 from src/iterativeSEM.hpp:14,
                 from src/bowtie_genome_map.cpp:1:
/usr/include/c++/4.8.2/istream:795:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
     class basic_iostream
           ^
In file included from src/common.hpp:6:0,
                 from src/bowtie_genome_map.cpp:2:
/usr/include/c++/4.8.2/sstream:502:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
     class basic_stringstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.8.2/sstream:502:11: error: use of deleted function ‘std::basic_stringbuf<char>::basic_stringbuf(const std::basic_stringbuf<char>&)’
/usr/include/c++/4.8.2/sstream:64:11: note: ‘std::basic_stringbuf<char>::basic_stringbuf(const std::basic_stringbuf<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_stringbuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /usr/include/c++/4.8.2/ios:43:0,
                 from /usr/include/c++/4.8.2/istream:38,
                 from /usr/include/c++/4.8.2/fstream:38,
                 from src/iterativeSEM.hpp:14,
                 from src/bowtie_genome_map.cpp:1:
/usr/include/c++/4.8.2/streambuf:802:7: error: ‘std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from src/common.hpp:6:0,
                 from src/bowtie_genome_map.cpp:2:
/usr/include/c++/4.8.2/sstream:64:11: error: within this context
     class basic_stringbuf : public basic_streambuf<_CharT, _Traits>
           ^
make: *** [obj/bowtie_genome_map.o] Error 1
`
Thank you a lot for your help,
Ayan

**Comment by aboyle** [comment]
You will need to use a newer version of gcc to compile. I think that this particular error was fixed in GCC v 5.0

**Comment by ai358** [comment]
Thank you very much! I used GCC v7.0 and it's perfectly installed.
