### ISSUE TITLE
Discrepancy in results using signal p-value and fold change over control ChIP data

### ISSUE THREAD

**Issue by annahutch** [Boyle-Lab/SEMpl#20]
Hi,

I have ran SEMpl for IKZF1 in GM12878 twice, using different ChIP-seq data as I am unsure of the recommended bigwig output to use.

Firstly, using the signal p-value bigwig file (ENCFF176OVL in https://www.encodeproject.org/experiments/ENCSR441VHN/) gives the following SEM plot. This finishes in just 12 iterations but has a Signal to background T-test [-log10(p-value)] of 1.57964.

![image](https://user-images.githubusercontent.com/42926930/108041799-f374e000-7036-11eb-8552-1d10f6419d38.png)

I then run SEMpl again using the same PWM and DNase data but using the fold change over control ChIP data (ENCFF405CHV in the same ENCODE experiment). This takes 59 iterations and has a Signal to background T-test [-log10(p-value)] of 3.074614.

![image](https://user-images.githubusercontent.com/42926930/108042260-7b5aea00-7037-11eb-8b49-9866fdcf8382.png)

As you can see the results differ quite substantially. I am more inclined to trust the data using the fold change over control ChIP data due to the significant t-test p-value, but comparing this to the PWM I used:

![image](https://user-images.githubusercontent.com/42926930/108042571-e4426200-7037-11eb-833a-ea0cfd56b8b4.png)

it doesn't seem possible that G can ablate binding at position 4 as this is the consensus nucleotide..

I also wonder why the results are so different when using the different ChIP-seq data files from the same ENCODE experiment.

Many thanks,
Anna

**Comment by aboyle** [comment]
Technically either bigwig track should work for the enrichment calculations - we used p-value tracks for everything though. This looks like either a low quality ChIP-seq experiment or the wrong starting motif. The FE track seemed to give a result that is converging on the top motif reported in factorbook as well so I think it is more likely that the motif for whatever is being ChIP'd is a mismatch: https://factorbook.org/experiment/ENCSR441VHN/motif
